---
title: "Merge coMethDMR meta-analysis and comb-p results."
author:
  - David Lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::html_document:
    highlight: breezedark
    theme: lumen
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(GenomicRanges)
  library(IRanges)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "AD-Aging-brain-sample-analysis")
code_dir <- file.path(analysis_dir, "code")
dataset_dir <- file.path(code_dir, "DATASETS")
rosmap_dir <- file.path(dataset_dir, "Rosmap")
bdr_dir <- file.path(dataset_dir, "BDR")
reference_dir <- file.path(code_dir, "Reference_Files")
mike_dir <- file.path(analysis_dir, "Mike")
```

# Get coMethDMR Data

## Load Significant coMethDMR Data

```{r cometh_load}
cometh_df <- read.csv(
  file = file.path(
    analysis_dir,
    "analysis-results",
    "meta_analysis",
    "meta_analysis_cometh_dmr_bacon.csv"
  )
)

cometh_df <- cometh_df %>%
  dplyr::filter(.data$direction_bacon %in% c("++", "--")) %>%
  dplyr::filter(.data$fdr_bacon_inclusive < 0.05) %>%
  dplyr::rename(DMR = "inputRegion") %>%
  tidyr::separate(
    .data$DMR,
    into = c("seqnames", "start", "end"),
    sep = ":|-",
    remove = FALSE
  ) %>%
  dplyr::mutate(start = as.integer(.data$start), end = as.integer(.data$end))

dim(cometh_df)
```

# get comb-p data

## Load Significant comb-p Data

```{r combp_load}
combp_df <- read.csv(
  file = file.path(mike_dir, "cnew.regions-p.bed.annotated.csv")
)

combp_df <- combp_df %>%
  dplyr::filter(.data$n_probes >= 3) %>%
  dplyr::filter(.data$z_sidak_p < 0.05) %>%
  dplyr::mutate(X.chrom = paste0("chr", .data$X.chrom)) %>%
  dplyr::mutate(DMR = paste0(.data$X.chrom, ":", .data$start, "-", .data$end)) %>%
  dplyr::select(
    combp_DMR = "DMR",
    combp_chrom = "X.chrom",
    combp_start = "start",
    combp_end = "end",
    combp_min_p = "min_p",
    combp_n_probes = "n_probes",
    combp_z_p = "z_p",
    combp_z_sidak_p = "z_sidak_p",
    "GREAT_annotation"
  )
combp_df$index <- 1:nrow(combp_df)

dim(combp_df)
```

## Get comb-p Directions

```{r combp_direction}
cpg_df <- read.csv(
  file.path(
    analysis_dir,
    "analysis-results",
    "meta_analysis",
    "meta_analysis_single_cpg_bacon.csv"
  )
) %>%
  dplyr::mutate(
    direction = ifelse(
      .data$estimate_bacon == 0,
      ".",
      ifelse(.data$estimate_bacon > 0, "+", "-")
    )
  ) %>%
  dplyr::select(
    "probe",
    "seqnames",
    "start",
    "end",
    "direction"
  )
cpg_df$index <- 1:nrow(cpg_df)

cpg_gr <- GenomicRanges::GRanges(
  seqnames = cpg_df$seqnames,
  ranges = IRanges::IRanges(start = cpg_df$start, end = cpg_df$end)
)
combp_gr <- GenomicRanges::GRanges(
  seqnames = combp_df$combp_chrom,
  ranges = IRanges::IRanges(
    start = combp_df$combp_start,
    end = combp_df$combp_end
  )
)

overlap_df <- GenomicRanges::findOverlaps(combp_gr, cpg_gr) %>%
  as.data.frame()
direction_df <- overlap_df %>%
  dplyr::left_join(cpg_df, by = c("subjectHits" = "index")) %>%
  dplyr::group_by(.data$queryHits) %>%
  dplyr::summarise(
    filter_direction = paste0(unique(.data$direction), collapse = ""),
    combp_direction = paste0(.data$direction, collapse = ""),
    combp_probes = paste0(.data$probe, collapse = ";")
  ) %>%
  dplyr::filter(.data$filter_direction %in% c("+", "-")) %>%
  dplyr::select(-"filter_direction")

combp_df <- combp_df %>%
  dplyr::filter(.data$index %in% direction_df$queryHits) %>%
  dplyr::left_join(direction_df, by = c("index" = "queryHits")) %>%
  dplyr::select(-"index")

dim(combp_df)
```

# Merge Results

## Merge Data

```{r merge}
combp_gr <- GenomicRanges::GRanges(
  seqnames = combp_df$combp_chrom,
  ranges = IRanges::IRanges(
    start = combp_df$combp_start,
    end = combp_df$combp_end
  )
)
cometh_gr <- GenomicRanges::GRanges(
  seqnames = cometh_df$seqnames,
  ranges = IRanges(start = cometh_df$start, end = cometh_df$end)
)

overlap_df <- GenomicRanges::findOverlaps(cometh_gr, combp_gr) %>%
  as.data.frame()
combp_df$index <- 1:nrow(combp_df)
cometh_df$index <- 1:nrow(cometh_df)

merge_df <- cometh_df %>%
  dplyr::inner_join(overlap_df, by = c("index" = "queryHits")) %>%
  dplyr::inner_join(combp_df, by = c("subjectHits" = "index")) %>%
  dplyr::select(-c("index", "seqnames", "start", "end", "subjectHits"))

dim(merge_df)
```

## Rearrange Columns

```{r rearrange}
merge_cols <- colnames(merge_df)
annotate_columns <- c(
  "DMR",
  "combp_DMR",
  "GREAT_annotation",
  "UCSC_RefGene_Group",
  "UCSC_RefGene_Accession",
  "UCSC_RefGene_Name",
  "Relation_to_Island",
  "state"
)
combp_columns <- merge_cols[stringr::str_starts(merge_cols, "combp_")]
combp_columns <- combp_columns[!(combp_columns %in% annotate_columns)]
assoc_columns <- merge_cols[!(merge_cols %in% c(annotate_columns, combp_columns))]

all_columns <- c(annotate_columns, combp_columns, assoc_columns)
merge_df <- merge_df[,all_columns]
```

## Show Merged Results

```{r display}
merge_df
```

# Save

```{r save}
write.csv(
  merge_df,
  file = file.path(
    analysis_dir,
    "analysis-results",
    "meta_analysis",
    "meta_analysis_summary.csv"
  ),
  row.names = FALSE
)
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>

