---
title: "Check DMR data against MIAMI-AD"
author:
  - David Lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::html_document:
    highlight: breezedark
    theme: lumen
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

# Set Up

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(tidyr)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "AD-Aging-brain-sample-analysis")
result_dir <- file.path(analysis_dir, "analysis-results")
ref_dir <- file.path(analysis_dir, "code", "Reference_Files")
result_dir <- file.path(analysis_dir, "analysis-results")
```

```{r}
dmr_df <- read.csv(
  file = file.path(
    analysis_dir,
    "analysis-results",
    "meta_analysis",
    "meta_analysis_summary.csv"
  )
)

dmr_probes <- dmr_df %>%
  dplyr::select("combp_probes") %>%
  dplyr::mutate(probes = stringr::str_split(.data$combp_probes, ";")) %>%
  tidyr::unnest(cols = "probes") %>%
  dplyr::pull("probes") %>%
  unique()

dnam_df <- read.csv(file = file.path(
  analysis_dir,
  "analysis-results",
  "meta_analysis",
  "meta_analysis_single_cpg_bacon.csv"
  )
)

cpg_df <- dnam_df %>%
  dplyr::select(
    CpG = "probe",
    chr = "seqnames",
    position = "start",
    "GREAT_annotation",
    estimate_cpg = "estimate_bacon",
    stdErr_cpg = "standard_error_bacon",
    pValue_cpg = "pvalue_final_bacon",
    direction_cpg = "direction_bacon"
  ) %>%
  dplyr::filter(.data$CpG %in% dmr_probes) %>%
  dplyr::mutate(direction_cpg = ifelse(.data$estimate_cpg > 0, "+", "-"))

dmr_df <- dmr_df %>%
  dplyr::select(
    DMR = "combp_DMR",
    GREAT_annotation_dmr = "GREAT_annotation",
    chromatin_state = "state",
    estimate_dmr = "estimate_bacon",
    stdErr_dmr = "standard_error_bacon",
    pValue_dmr = "pvalue_final_bacon",
    direction_dmr = "direction_bacon",
    CpG = "combp_probes"
  ) %>%
  dplyr::mutate(
    direction_dmr = ifelse(.data$direction_dmr == "++", "+", "-")
  ) %>%
  dplyr::mutate(
    CpG = stringr::str_split(CpG, ";")
  ) %>%
  tidyr::unnest("CpG")

annot_df <- dmr_df %>%
  dplyr::inner_join(cpg_df, by = "CpG") %>%
  dplyr::select(
    "DMR",
    "CpG",
    "GREAT_annotation_dmr",
    "chromatin_state",
    "chr",
    "position",
    "GREAT_annotation",
    "estimate_dmr",
    "stdErr_dmr",
    "pValue_dmr",
    "direction_dmr",
    "estimate_cpg",
    "stdErr_cpg",
    "pValue_cpg",
    "direction_cpg"
  ) %>%
  dplyr::arrange(.data$pValue_cpg) %>%
  dplyr::arrange(.data$pValue_dmr)
```


```{r}
ext_df <- readxl::read_excel(
  file.path(ref_dir, "CpG Statistics.xlsx"),
  sheet = "Individual Datasets"
) %>%
  dplyr::rename(cohort = "sample_group")

legend_df <- readxl::read_excel(
  file.path(ref_dir, "Study_Legends.xlsx")
) %>%
  dplyr::select(
    dataset = "Dataset",
    "Description",
    "Author",
    "Year",
    "PMID"
  )

ext_df <- ext_df %>%
  dplyr::left_join(legend_df) %>%
  dplyr::filter(.data$pValue < 1.46e-5)
```

```{r}
sig_genes <- ext_df %>%
  dplyr::select("CpG", "direction") %>%
  dplyr::left_join(cpg_df %>% dplyr::select("CpG", "direction_cpg")) %>%
  dplyr::distinct()

counts <- table(sig_genes$CpG)
cpgs <- names(counts)[counts == 1]
sig_genes <- sig_genes %>%
  dplyr::filter(.data$CpG %in% cpgs) %>%
  dplyr::filter(.data$direction == .data$direction_cpg)
ext_df <- ext_df %>%
  dplyr::filter(.data$CpG %in% cpgs) %>%
  dplyr::arrange(.data$pValue)
```

```{r}
final_df <- annot_df %>%
  dplyr::inner_join(ext_df, by = "CpG")

write.csv(
  final_df,
  file = file.path(
    result_dir, 
    "MIAMI-AD_validation",
    "DMR_Genes_External_Significance.csv"
  ),
  row.names = FALSE,
  quote = TRUE
)
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>

