---
title: "Plot correlation between brain and blood samples of key CpGs in LONDON Dataset"
author:
  - David Lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::html_document:
    highlight: breezedark
    theme: lumen
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(doParallel)
})

base_dir <- "~/TBL Dropbox/David Lukacsovich"
analysis_dir <- file.path(base_dir, "AD-Aging-brain-sample-analysis")
result_dir <- file.path(analysis_dir, "analysis-results")
london_dir <- file.path(base_dir, "DATASET/LONDON")
pheno_dir <- file.path(london_dir, "Phenotype/processed")
beta_dir <- file.path(london_dir, "DNAm/pca_filtering")
resid_dir <- file.path(analysis_dir, "code", "DATASETS", "LONDON", "residuals")
code_dir <- file.path(analysis_dir, "code")
reference_dir <- file.path(code_dir, "Reference_Files")
plot_dir <- file.path(analysis_dir, "analysis-results", "plots")
```

## Define Functions

```{r functions}
brain_lmF <- function(mval) {
  fitE <- stats::lm(
    mval ~ brain_age + sex + neuron_prop + brain_slide,
    data = pheno_df,
    na.action = na.exclude
  )
  
  stats::residuals(fitE)
}

blood_lmF <- function(mval) {
  fitE <- stats::lm(
    mval ~ blood_age + sex + blood_slide + B + NK + CD4T + CD8T +
      Mono + Neutro + Eosino,
    data = pheno_df,
    na.action = na.exclude
  )
  
  stats::residuals(fitE)
}

get_corr_vals <- function(mat_x, mat_y) {
  corr_vals <- plyr::adply(
    seq_len(nrow(mat_x)),
    .margins = 1,
    .fun = function(row) {
      spearman_cor <- cor.test(
        mat_x[row,], mat_y[row,], method = "spearman"
      )
      
      data.frame(
        spearman_cor = spearman_cor$estimate,
        pvalue = spearman_cor$p.value,
        rho = round(spearman_cor$estimate, digits = 3),
        psig = formatC(spearman_cor$p.value, format = "e", digits = 2),
        stringsAsFactors = FALSE
      )
    }, .id = NULL
  )
  
  corr_vals <- corr_vals %>%
    dplyr::mutate(
      cpg = row.names(mat_x),
      .before = "spearman_cor"
    ) %>%
    tibble::column_to_rownames(var = "cpg")
  
  corr_vals
}
```

# Get Data

## Load London Data

```{r london_load}
brain_pheno_df <- readRDS(
  file.path(pheno_dir, "pheno107_PFC_withNeuronProp_withStageExclude_df.RDS")
) %>%
  dplyr::select(
    brain_sample = "sample",
    subject_id = "subject.id",
    brain_age = "age.brain",
    "sex",
    brain_slide = "slide",
    neuron_prop = "prop.neuron"
  ) %>%
  dplyr::mutate(
    subject_id = as.character(.data$subject_id),
    brain_age = as.numeric(.data$brain_age),
    sex = as.character(.data$sex),
    neuron_prop = as.numeric(.data$neuron_prop),
    brain_slide = as.character(.data$brain_slide)
  )
blood_pheno_df <- readRDS(
  file.path(pheno_dir, "pheno_BLOOD_withBloodProp_withStatusExclude_df.rds")
) %>%
  dplyr::select(
    blood_sample = "sample",
    subject_id = "subject.id",
    blood_age = "age.blood",
    "sex",
    blood_slide = "slide",
    "B",
    "NK",
    "CD4T",
    "CD8T",
    "Mono",
    "Neutro",
    "Eosino"
  ) %>%
  dplyr::mutate(
    subject_id = as.character(.data$subject_id),
    blood_age = as.numeric(.data$blood_age),
    sex = as.character(.data$sex),
    blood_slide = as.character(.data$blood_slide),
    B = as.numeric(.data$B),
    NK = as.numeric(.data$NK),
    CD4T = as.numeric(.data$CD4T),
    CD8T = as.numeric(.data$CD8T),
    Mono = as.numeric(.data$Mono),
    Neutro = as.numeric(.data$Neutro),
    Eosino = as.numeric(.data$Eosino)
  )

brain_beta_mat <- readRDS(
  file.path(
    beta_dir, "BRAIN", "London_PFC_QNBMIQ_PCfiltered_withStageExclude.RDS"
  )
)

blood_beta_mat <- readRDS(
  file.path(
    beta_dir, "BLOOD", "London_QNBMIQ_PCfiltered_withStatusExclude.RDS"
  )
)
```

## Align Data

```{r london_align}
pheno_df <- brain_pheno_df %>%
  dplyr::select(-"sex") %>%
  dplyr::inner_join(blood_pheno_df, by = "subject_id")

cpgs <- intersect(row.names(brain_beta_mat), row.names(blood_beta_mat))
brain_beta_mat <- brain_beta_mat[cpgs,pheno_df$brain_sample]
blood_beta_mat <- blood_beta_mat[cpgs,pheno_df$blood_sample]
```

## Filter to Target CpGs

```{r london_filter}
cpgs <- c("cg10752406", "cg19990651", "cg25045942", "cg01748892")

brain_beta_mat <- brain_beta_mat[cpgs,]
blood_beta_mat <- blood_beta_mat[cpgs,]
```

# Get Residuals

## Brain Residuals

```{r london_residuals_brain}
brain_mval_mat <- log2( brain_beta_mat / (1 - brain_beta_mat))

doParallel::registerDoParallel(8)
brain_resid <- plyr::adply(
  brain_mval_mat,
  1,
  .fun = brain_lmF,
  .progress = "time",
  .parallel = TRUE
)
doParallel::stopImplicitCluster()

brain_resid <- brain_resid %>%
  tibble::column_to_rownames("X1")
colnames(brain_resid) <- colnames(brain_beta_mat)
brain_resid <- as.matrix(brain_resid)
```

## Blood Residuals

```{r london_residuals_blood}
blood_mval_mat <- log2( blood_beta_mat / (1 - blood_beta_mat))

doParallel::registerDoParallel(8)
blood_resid <- plyr::adply(
  blood_mval_mat,
  1,
  .fun = blood_lmF,
  .progress = "time",
  .parallel = TRUE
)
doParallel::stopImplicitCluster()

blood_resid <- blood_resid %>%
  tibble::column_to_rownames("X1")
colnames(blood_resid) <- colnames(blood_beta_mat)
blood_resid <- as.matrix(blood_resid)
```

## Get Correlation Statistics

```{r}
corr_df <- get_corr_vals(blood_resid, brain_resid)
```

# Plot Residuals

```{r, fig.width=9, fig.height = 9}
plot_probe_residuals <- function(blood_resid, brain_resid, corr_df, probe) {
  plot_df <- data.frame(
    blood = as.numeric(blood_resid[probe,]),
    brain = as.numeric(brain_resid[probe,])
  )
  
  label <- paste0(
    "Correlation = ", corr_df[probe,]$rho,
    "\np-value = ", corr_df[probe,]$psig
  )
  
  ggplot2::ggplot(
    plot_df,
    mapping = ggplot2::aes(x = brain, y = blood)
  ) +
    ggplot2::geom_point() +
    ggplot2::theme_bw() +
    ggplot2::geom_smooth(method='lm', se = FALSE, color = "red") +
    ggplot2::xlab("residuals of brain DNAm level") +
    ggplot2::ylab("residuals of blood DNAm level") +
    ggplot2::ggtitle(probe) +
    ggplot2::annotation_custom(
      grid::textGrob(
        label,
        0.02,
        0.98,
        hjust = 0,
        vjust = 1,
        gp = grid::gpar(fontsize = 10),
      )
    )
    
}

p1 <- plot_probe_residuals(blood_resid, brain_resid, corr_df, "cg10752406")
p2 <- plot_probe_residuals(blood_resid, brain_resid, corr_df, "cg19990651")
p3 <- plot_probe_residuals(blood_resid, brain_resid, corr_df, "cg25045942")
p4 <- plot_probe_residuals(blood_resid, brain_resid, corr_df, "cg01748892")

pdf(
  file.path(plot_dir, "BDR_Regression_Supplementary_Plots.pdf"),
  width = 9,
  height = 9,
  onefile = TRUE
)
gridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)
dev.off()

gridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)
```


# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
